.github/workflows/label-new-issues.yml

name: Label New Issues as "To Do"
on:
  issues:
    types: [opened]
permissions:
  issues: write  # Explicitly grants write permission to manage issues
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Label new issue as "To Do"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "To Do"
